name: Continuous Integration Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: "run tests"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "checkout repository"

      - name: 'Install Deps'
        run: npm install

      - name: 'run tests'
        run: npm run test
